### ISSUE TITLE
Questions about DEGs

### ISSUE THREAD

**Issue by jincanke** [AmichayAfriat/SpatioTemporal_malaria_liver_stage_atlas#1]
Hi, congratulations! I noticed in your paper, you said 'For differential gene expression analysis and pathway enrichment, the raw data was normalized to relative counts per cell in MATLAB R2019a by dividing by the sum of all genes that individually take up less than 0.01 of the cellular summed UMIs when averaged over all cells.'  I don't understand why you are doing this step and why not just use log-Normalized data?  In my opinion, is this a way to filter out some extremely high expression genes?

**Comment by AmichayAfriat** [comment]
Log-normalizing is dividing counts for each gene in the cell by the total counts for that cell and multiplying by a factor followed by natural-log transform. This is better for visualization but loses some fine details, so it was not used for DGE.
Those genes are not filtered out, but we don't want overly expressed genes to dominate all the data. Typically those are overrepresented due to technical limitations of single-cell library preparation practice (mainly the last stages of amplifications).

**Comment by jincanke** [comment]
Thanks for your answer! Sorry, I'm still a little confused, single-cell RNA sequencing is based on UMI counting and is not affected by amplification, maybe I'm missing something, could you help me understand?

**Comment by AmichayAfriat** [comment]
Not a problem!

Even with UMIs highly expressed genes would be more represented than if you would look into their actual numbers in the tissue (like in smFISH for example). In order not to drown out your normalized data with these artifacts you usually normalize in a differential manner as I indicated in the paper.
Basically, only a very small number of genes is affected by this normalization since most genes don't go nearly as high as 0.01 (notable example in hepatocytes is Alb), so you really get very similar results if you just normalize to the total sums, it's just helps you see differences better in gene expressing on the low side.
If you want the full code for this kind of normalization the matlab code is in https://zenodo.org/record/7081863#.Y34Wo7dOmNw
Under Fig2_EDF4_plots.m

Hope that helps!

Amichay


________________________________
